name: Copy CSV

on:
  push:
  workflow_dispatch:
  schedule:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Scrape
      run: |        
        curl 'https://mappingsupport.com/p/surf_gis/list-federal-state-county-city-GIS-servers.csv' > ./list-federal-state-county-city-GIS-servers.csv
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
